project_id = "mxsnnxnqzrdydcpzdqmu"

[functions]
  [functions.auth-email-hook]
    verify_jwt = false

  [functions.iniciar-sesion]
    verify_jwt = false

  [functions.preview-transactional-email]
    verify_jwt = false

  [functions.avisos-seguridad]
    verify_jwt = false
